# Generated by Django 5.2.8 on 2025-11-11 10:06

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models
import django.contrib.postgres.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user account should be considered active.', verbose_name='active')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('first_name', models.CharField(blank=True, max_length=150)),
                ('last_name', models.CharField(blank=True, max_length=150)),
                ('role', models.CharField(choices=[('resident', 'Resident'), ('authority', 'Authority')], default='resident', max_length=10)),
                ('phone_number', models.CharField(blank=True, help_text='Used for SMS alerts', max_length=20, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('geom_json', models.TextField(default='', help_text='GeoJSON coordinates for the ward boundary')),
                ('current_risk_level', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Low', max_length=10)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('population', models.IntegerField(default=0)),
                ('critical_infrastructure', models.JSONField(default=dict, help_text='Hospitals, schools, etc.')),
                ('safe_zones', models.JSONField(default=dict, help_text='Evacuation points')),
            ],
        ),
        migrations.CreateModel(
            name='CrowdReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_text', models.TextField(default='No report text provided.', help_text='Detailed description of the flood report.')),
                ('location_description', models.CharField(default='No location description provided', help_text="e.g., 'Corner of Main St.'", max_length=255)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Validated', 'Validated'), ('Rejected', 'Rejected')], default='Pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('photos', django.contrib.postgres.fields.ArrayField(base_field=models.URLField(), blank=True, help_text='Cloud storage URLs for photos', null=True, size=None)),
                ('reliability_score', models.FloatField(default=0.5, help_text='0-1 score based on user history')),
                ('upvotes', models.IntegerField(default=0)),
                ('downvotes', models.IntegerField(default=0)),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ward', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.ward')),
            ],
        ),
        migrations.CreateModel(
            name='WeatherDataLake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('KMD', 'Kenya Meteorological Department'), ('GPM', 'Global Precipitation Measurement'), ('CHIRPS', 'Climate Hazards Group'), ('OPEN_METEO', 'Open-Meteo API')], max_length=20)),
                ('raw_data', models.JSONField(help_text='Raw weather data from source')),
                ('rainfall_mm', models.FloatField(blank=True, null=True)),
                ('temperature_celsius', models.FloatField(blank=True, null=True)),
                ('humidity_percent', models.FloatField(blank=True, null=True)),
                ('wind_speed_kmh', models.FloatField(blank=True, null=True)),
                ('cloud_cover_percent', models.FloatField(blank=True, null=True)),
                ('soil_moisture', models.FloatField(blank=True, null=True)),
                ('vegetation_index', models.FloatField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('ingested_at', models.DateTimeField(auto_now_add=True)),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weather_data_lake', to='core.ward')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SystemAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('channel', models.CharField(choices=[('SMS', 'SMS via Twilio'), ('WHATSAPP', 'WhatsApp'), ('EMAIL', 'Email'), ('IN_APP', 'In-App Notification'), ('WEB_PUSH', 'Web Push')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('FAILED', 'Failed'), ('ACKNOWLEDGED', 'Acknowledged')], default='PENDING', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('external_id', models.CharField(blank=True, help_text='ID from external service', max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FloodPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicted_risk_level', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=10)),
                ('confidence_score', models.FloatField(help_text='0-1 confidence')),
                ('probability_low', models.FloatField()),
                ('probability_medium', models.FloatField()),
                ('probability_high', models.FloatField()),
                ('features_used', models.JSONField()),
                ('model_version', models.CharField(max_length=20)),
                ('valid_from', models.DateTimeField()),
                ('valid_until', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='core.ward')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CrowdsourcedDataLake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_urls', django.contrib.postgres.fields.ArrayField(base_field=models.URLField(), blank=True, null=True, size=None)),
                ('water_level_estimated', models.FloatField(blank=True, null=True)),
                ('affected_area_sqm', models.FloatField(blank=True, null=True)),
                ('severity_score', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], help_text='1-10 severity scale')),
                ('affected_structures', models.IntegerField(default=0)),
                ('people_affected', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='data_lake_entry', to='core.crowdreport')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_level', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=10)),
                ('message_text', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='core.ward')),
            ],
        ),
        migrations.AddField(
            model_name='systemalert',
            name='prediction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='core.floodprediction'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='subscribed_wards',
            field=models.ManyToManyField(blank=True, related_name='subscribers', to='core.ward'),
        ),
        migrations.AddIndex(
            model_name='weatherdatalake',
            index=models.Index(fields=['ward', 'timestamp'], name='core_weather_ward_ti_idx'),
        ),
        migrations.AddIndex(
            model_name='weatherdatalake',
            index=models.Index(fields=['source', 'timestamp'], name='core_weather_source__idx'),
        ),
        migrations.AddIndex(
            model_name='ward',
            index=models.Index(fields=['current_risk_level'], name='core_ward_current__idx'),
        ),
        migrations.AddIndex(
            model_name='floodprediction',
            index=models.Index(fields=['ward', 'valid_from'], name='core_flood_p_ward_v_idx'),
        ),
    ]
