# Generated by Django 5.2.8 on 2025-11-26 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_weatherdata_alter_customuser_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalFloodEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('date_occurred', models.DateField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('risk_level', models.CharField(choices=[('Low', 'Low Risk'), ('Medium', 'Medium Risk'), ('High', 'High Risk')], max_length=20)),
                ('estimated_casualties', models.IntegerField(default=0)),
                ('estimated_displaced', models.IntegerField(default=0)),
                ('estimated_damage_value', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('rainfall_mm', models.FloatField(help_text='Rainfall recorded during event')),
                ('temperature_celsius', models.FloatField(blank=True, null=True)),
                ('humidity_percent', models.IntegerField(blank=True, null=True)),
                ('wind_speed_kmh', models.FloatField(blank=True, null=True)),
                ('primary_cause', models.CharField(choices=[('heavy_rainfall', 'Heavy Rainfall'), ('poor_drainage', 'Poor Drainage'), ('river_overflow', 'River Overflow'), ('dam_failure', 'Dam Failure'), ('poor_infrastructure', 'Poor Infrastructure'), ('climate_change', 'Climate Change')], max_length=100)),
                ('data_source', models.CharField(help_text='Source of data (e.g., NDMA, news, reports)', max_length=255)),
                ('source_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('affected_wards', models.ManyToManyField(related_name='historical_floods', to='core.ward')),
            ],
            options={
                'verbose_name': 'Historical Flood Event',
                'verbose_name_plural': 'Historical Flood Events',
                'ordering': ['-date_occurred'],
            },
        ),
        migrations.CreateModel(
            name='SatelliteFloodData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('satellite_source', models.CharField(choices=[('sentinel_1', 'Sentinel-1 SAR'), ('sentinel_2', 'Sentinel-2 Optical'), ('landsat_8', 'Landsat 8'), ('modis', 'MODIS')], max_length=100)),
                ('capture_date', models.DateField()),
                ('event_status', models.CharField(choices=[('pre_flood', 'Pre-Flood'), ('during_flood', 'During Flood'), ('post_flood', 'Post-Flood')], max_length=20)),
                ('inundated_area_sqkm', models.FloatField()),
                ('water_depth_estimate_m', models.FloatField(blank=True, null=True)),
                ('confidence_percent', models.IntegerField(help_text='Data confidence 0-100%')),
                ('raw_data_url', models.URLField(help_text='Link to raw satellite data')),
                ('processed_geojson', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('historical_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='satellite_data', to='core.historicalfloodevent')),
            ],
            options={
                'ordering': ['-capture_date'],
            },
        ),
        migrations.CreateModel(
            name='ClimatePatternData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField(choices=[(1, 'Month 1'), (2, 'Month 2'), (3, 'Month 3'), (4, 'Month 4'), (5, 'Month 5'), (6, 'Month 6'), (7, 'Month 7'), (8, 'Month 8'), (9, 'Month 9'), (10, 'Month 10'), (11, 'Month 11'), (12, 'Month 12')])),
                ('year', models.IntegerField()),
                ('avg_rainfall_mm', models.FloatField()),
                ('avg_temperature_celsius', models.FloatField()),
                ('avg_humidity_percent', models.IntegerField()),
                ('has_flood_occurred', models.BooleanField(default=False)),
                ('flood_probability', models.FloatField(default=0.0, help_text='0-1 probability')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='climate_patterns', to='core.ward')),
            ],
            options={
                'ordering': ['-year', 'month'],
                'unique_together': {('ward', 'month', 'year')},
            },
        ),
        migrations.CreateModel(
            name='FloodHistoricalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('flood_count', models.IntegerField(default=0)),
                ('avg_rainfall_mm', models.FloatField(default=0)),
                ('max_rainfall_mm', models.FloatField(default=0)),
                ('total_affected', models.IntegerField(default=0)),
                ('total_displaced', models.IntegerField(default=0)),
                ('total_casualties', models.IntegerField(default=0)),
                ('flood_risk_score', models.FloatField(help_text='0-100 risk score')),
                ('vulnerability_index', models.FloatField(help_text='0-100 vulnerability score')),
                ('inundation_area_sqkm', models.FloatField(blank=True, null=True)),
                ('vegetation_loss_percent', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historical_data', to='core.ward')),
            ],
            options={
                'ordering': ['-year'],
                'unique_together': {('ward', 'year')},
            },
        ),
        migrations.AddIndex(
            model_name='historicalfloodevent',
            index=models.Index(fields=['-date_occurred'], name='core_histor_date_oc_dab76c_idx'),
        ),
        migrations.AddIndex(
            model_name='historicalfloodevent',
            index=models.Index(fields=['risk_level'], name='core_histor_risk_le_3e4503_idx'),
        ),
    ]
