# Generated by Django 5.2.8 on 2025-11-26 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_historicalfloodevent_satelliteflooddata_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crowdreport',
            name='photos',
            field=models.ImageField(blank=True, help_text='Upload a photo of the flood situation', null=True, upload_to='flood_reports/%Y/%m/%d/'),
        ),
    ]
