# Generated by Django 5.2.8 on 2025-12-02 12:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_emaillog'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('validated', 'Validated'), ('rejected', 'Rejected')], max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Admin notes sent to user')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='core.crowdreport')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
